### ISSUE TITLE
Auto documentation not generated for BatchDx, ObjectsDx

### ISSUE THREAD

**Issue by devopsokdone** [pubnub/dart#11]
Just to bring your attention to this, even though these modules are documented in the code but when referring to the auto-generated documentation it is missing, links below for your reference. Due to this even though the functionality is available we din't know until after discovering inside the code.

https://pub.dev/documentation/pubnub/latest/pubnub/PubNub/objects.html
https://pub.dev/documentation/pubnub/latest/pubnub/PubNub/batch.html

**Comment by are** [comment]
Hi, thanks so much for reporting this. I will make sure that those are properly referenced in our next release.
