### ISSUE TITLE
Fetch messages with message actions

### ISSUE THREAD

**Issue by edissonaguilar** [pubnub/dart#12]
Hi, I was searching in the documentation and I didn't find how to get history of a channel with actions like in JS:

`pubnub.fetchMessages(
  {
    channels: ['ch-1'],
    start: "15343325214676133",
    includeMessageActions: true,
    count: 25
  },
  (status, response) => {
    // handle response
  }
);`

Thanks!

**Comment by mohitpubnub** [comment]
Hi! Thank You for opening this issue. We are about to make a release `v1.4.4` which also includes this feature.
So there will be parameter `includeMessageActions` in batch history api.
