### ISSUE TITLE
Getting error while flutter pub get  affected by advisory: [^0]

### ISSUE THREAD

**Issue by mehtahardikr** [pubnub/dart#131]
While running this `flutter pub get` command getting error `affected by advisory: [^0]`

and its returns the following link : https://github.com/advisories/GHSA-5844-q3fc-56rh

Is there anything that need to change from App side ? Please guide on us.

**Comment by mohitpubnub** [comment]
@mehtahardikr which version of PubNub Dart SDK your application is using?
as the link suggests, it's recommended to use PubNub dart sdk version > 4.3.0.

Still, We always recommend to use latest version of sdk to avoid such issues.
