### ISSUE TITLE
Upgrading to v2.0.0 failing

### ISSUE THREAD

**Issue by devopsokdone** [pubnub/dart#14]
When trying to upgrade SDK version to 2.0.0 giving following error:

Because pubnub >=1.4.4 depends on xml ^4.3.0 which depends on meta ^1.2.0, pubnub >=1.4.4 requires meta ^1.2.0.
And because every version of flutter from sdk depends on meta 1.1.8, pubnub >=1.4.4 is incompatible with flutter from sdk.
So, because appname_pubnub depends on both flutter any from sdk and pubnub ^2.0.0, version solving failed.
pub get failed (1; So, because appname_pubnub depends on both flutter any from sdk and pubnub ^2.0.0, version solving failed.)

Our Flutter version:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-IN)

We checked the pubsec.yaml file of SDK and the version of package "meta" is 1.1.0 and it seems minimum required is 1.1.8 or 1.2.0 due to which upgrade is failing.

**Comment by devopsokdone** [comment]
Quick message to check if this will take time to resolve as our testing for history and reconnection is dependent on this release.

**Comment by mohitpubnub** [comment]
Most probably next week this will get fixed!
May be @are  will communicate exact date soon.

**Comment by mohitpubnub** [comment]
This fix won't work yet! Please wait for next upgrade.
