### ISSUE TITLE
Exception while adding device for push notification

### ISSUE THREAD

**Issue by aadil058** [pubnub/dart#2]
Call that caused the exception -
```
await pubnub.addPushChannels(fcmToken, PushGateway.gcm, Set.of(['chName']), using: 'wellowise');
// Same exception for listPushChannels call
```

```
Exception -
E/flutter ( 3660): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PubNubException: Cannot decode string as JSON
E/flutter ( 3660): #0      new PubNubException (package:pubnub/src/core/exceptions.dart:6:29)
E/flutter ( 3660): #1      new ParserException (package:pubnub/src/core/parse.dart:4:39)
E/flutter ( 3660): #2      PubNubParserModule.decode (package:pubnub/src/parser/parser.dart:11:13)
E/flutter ( 3660): #3      defaultFlow (package:pubnub/src/dx/_utils/default_flow.dart:29:35)
E/flutter ( 3660): <asynchronous suspension>
E/flutter ( 3660): #4      PushNotificationDx.addPushChannels (package:pubnub/src/dx/push/push.dart:75:12)
```

**Comment by aadil058** [comment]
I tried debug methods listed on [](https://support.pubnub.com/support/solutions/articles/14000043605-how-can-i-troubleshoot-my-push-notification-issues-) and concluded that my device was not registered.

**Comment by mohitpubnub** [comment]
Yes. This should be fixed in SDK.
Meanwhile just make sure that you have successfully enabled Push Notifications feature for your subscribe key from PubNub Dashboard.

**Comment by aadil058** [comment]
Done that. I am using unofficial flutter pubnub plugin [flutter_pubnub](https://pub.dev/packages/flutter_pubnub) as a workaround to receive push notifications for now. It's working great.

**Comment by pushpendraKh** [comment]
I am not able to access `PushGateway` type. Any idea what am I missing?

**Comment by mohitpubnub** [comment]
@pushpendraKh  Yes..this will be fixed in upcoming release!

At this moment, You can add import statement and make it work:
`import 'package:pubnub/src/dx/_endpoints/push.dart';`
