### ISSUE TITLE
Method missing or not added in 3.0.0

### ISSUE THREAD

**Issue by mehtahardikr** [pubnub/dart#22]
hey @are  : 

one question

is this added ?

```

 pubnub.supervisor.events.listen((event) {
      // Check NetworkIsDownEvent OR NetworkIsUpEvent
    });
```

and is this not added as in your comments you told me to use ?
```
pubnub.signals.networkIsConnected.listen((isUp) {
  if (isUp) {
    print('network reconnected');
  } else {
    print('network disconnected');
  }
});
```
Please refer this : 
https://github.com/pubnub/dart/issues/19

**Comment by are** [comment]
It is available as `pubnub.signals` (documentation here: https://pub.dev/documentation/pubnub/latest/core/Signals-class.html).

**Comment by mehtahardikr** [comment]
okay got that. thank you !
