### ISSUE TITLE
Pubnub.subscribe get error exception

### ISSUE THREAD

**Issue by slorop41314** [pubnub/dart#28]
I try pubnub.subscribe method and it gets an error exception on subscibribe_loop.dart from the library.

![Screenshot 2020-12-19 at 22 35 10](https://user-images.githubusercontent.com/52713279/102693106-b82e7e80-424a-11eb-83c0-71a5dca1316d.png)

This is my code.

_pubnub = PubNub(defaultKeyset:keyset)

`Subscription subscribeChannels({
    Set<String> channels,
    Set<String> channelGroups,
  }) {

    Subscription result = this._pubnub.subscribe(
          channels: channels,
          channelGroups: channelGroups,
        );

    return result;
  }`

**Comment by are** [comment]
Hi! Thanks for reporting the issue. We are actively working on removing the `dio` dependency so this will be resolved by this. However, there is an issue with the flutter debugger, take a look here: https://github.com/pubnub/dart/issues/20#issuecomment-700818107

**Comment by slorop41314** [comment]
I seee, thanks alot for your answer. Will waiting for this issue to be solved. Anyway, great package!

**Comment by are** [comment]
We have released a new version `3.1.0` that contains a fix. Let us know if the issue still persists.
