### ISSUE TITLE
How to listen to typings events(signals) ? 

### ISSUE THREAD

**Issue by Adidi** [pubnub/dart#35]
I see in the object i can send signal through pubnub instance like this:
```dart
pubnub.signal('channel', {'text': 'typing_on', 'user': 'Liran'});
```

How can I receive this signal in a channel ? I try to find and play with it and could not succeed

Thanks

**Comment by are** [comment]
Hi! You can listen to signals just like you subscribe to normal messages. The `Envelope` has a [messageType](https://pub.dev/documentation/pubnub/latest/pubnub/Envelope/messageType.html) field that allows you to differentiate between normal messages and signals.

**Comment by Adidi** [comment]
Thank you!
You should really improve your dart docs so we can enjoy your amazing library.
If you like dart sdk page on pubnub its really poor comparing to other SDKs and trivial stuff to do with the sdk is not clear enough on how to acheive those...

**Comment by are** [comment]
Yes, we are in progress with updating the Dart docs on our page. Thank you for using it tho! We really appreciate all the feedback!
