### ISSUE TITLE
How to add debug logging to my pubnub client ?

### ISSUE THREAD

**Issue by Adidi** [pubnub/dart#37]
In this [troubleshooting docs](https://www.pubnub.com/docs/sdks/dart/troubleshooting) the pubnub instance does not have `log` property so this code is not working:
```dart
  pubnub = PubNub(
      defaultKeyset: Keyset(
        subscribeKey: Config.pubnubSubscribeKey,
        publishKey: Config.pubnubPublishKey,
        uuid: UUID(meId),
      ),
      networking: NetworkingModule(
        retryPolicy: RetryPolicy.exponential(),
      ),
    );

    pubnub.log.level = Level.ALL;
    pubnub.onRecord.listen((record) {
      print('${record.level.name}: ${record.time}: ${record.message}');
    });
```

What am i missing ?

**Comment by are** [comment]
The documentation in PubNub docs is not up to date. Please refer to the example in the examples directory: https://github.com/pubnub/dart/blob/master/pubnub/example/logging.dart
