### ISSUE TITLE
Sound-null-safety or NNR feature request.

### ISSUE THREAD

**Issue by alecxandrys** [pubnub/dart#39]
Good day,
Is there any plan to migrate to "sound-null-safety" (or NNR)?

**Comment by are** [comment]
Hi there! Yes, we were anticipating Null Safety, but we were blocked by our dependencies. We do plan to support NNBD soon, however I don't have any concrete date to give.

**Comment by pushpendraKh** [comment]
@are all dependencies are migrated to Null Safety.. 

[async](https://pub.dev/packages/async): 2.5.0 (migrated to null safety)
[cbor](https://pub.dev/packages/async): 4.0.0 (migrated to null safety)
[convert](https://pub.dev/packages/convert): 3.0.0 (migrated to null safety)
[crypto](https://pub.dev/packages/crypto): 3.0.0 (migrated to null safety)
[encrypt](https://pub.dev/packages/encrypt/versions/5.0.0-beta.1): 5.0.0-beta.1 (migrated to null safety), hope soon they bump the version to [5.0.0](https://github.com/leocavalcante/encrypt/issues/200#issuecomment-802651400), towards stability. But this should not stop the migration. 
[form_data](https://pub.dev/packages/form_data/versions/1.0.0-nullsafety.1): 1.0.0-nullsafety.1 (migrated to null safety), hope @are (you) bump the version to [1.0.0](https://github.com/leocavalcante/encrypt/issues/200#issuecomment-802651400), towards stability. But this should not stop the migration. 
[meta](https://pub.dev/packages/meta): 1.3.0 (migrated to null safety)
[pedantic](https://pub.dev/packages/pedantic): 1.11.0 (migrated to null safety)
[pool](https://pub.dev/packages/pool): 1.5.0 (migrated to null safety)
[xml](https://pub.dev/packages/xml): 5.0.2 (migrated to null safety)
[test](https://pub.dev/packages/test) : 1.16.8 (migrated to null safety)

Except [gherkin](https://pub.dev/packages/gherkin) - dev dependency but here is the [drafted incomplete PR](https://github.com/jonsamwell/dart_gherkin/pull/30), hope for it to soon be ready

Is it possible to go without gherkin for the time being?

**Comment by are** [comment]
@pushpendraKh That is correct! All of our dependencies are ready and we are in the process of migrating the SDK to Null Safety.

**Comment by jakubswietek** [comment]
Hello guys! Any updates on this? Is there a target date for releasing the pubnub plugin with null safety?

**Comment by are** [comment]
We cannot share a specific date, but the work is still continuing. Null Safety is a very big update for us and we want to make sure it is done right.

**Comment by are** [comment]
Heads up! We have released a beta version of our Null Safe SDK. Please give it a try! Keep in mind that some interfaces have changed and there maybe some bugs, so please report them!

https://pub.dev/packages/pubnub/versions/4.0.0-beta.0
