### ISSUE TITLE
pubnub: ^3.2.0 version solving failed.

### ISSUE THREAD

**Issue by unoravi** [pubnub/dart#41]
Because of Pubnub version (3.2.0),  I am facing an error while upgrading other dependencies in my project. It seems that this error is because pubnub 3.2.0 depends on crypto ^2.1.5 and other dependencies supports crypto ^3.0.1. So pubnub should support the latest one too.

flutter pub get
```
Because pubnub 3.2.0 depends on crypto ^2.1.5 and no versions of pubnub match >3.2.0 <4.0.0, pubnub ^3.2.0 requires crypto ^2.1.5.
So, because signageplayer depends on both pubnub ^3.2.0 and crypto ^3.0.1, version solving failed.
pub get failed (1; So, because demoproject depends on both pubnub ^3.2.0 and crypto ^3.0.1, version solving failed.)
```

List of  Few Dependencies Facing an issue : 
- universal_html: ^2.0.8
- wakelock: ^0.5.0+2
- archive: ^3.1.2

Look into this issue quickly and do the needful.

Thanks

**Comment by are** [comment]
Hi, this is unfortunately a very common problem in Dart ecosystem.

There is a temporary solution that can unblock you - use [dependency overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides) temporarily to make your application work. Example:
```# pubspec.yaml
dependency_overrides:
    crypto: '3.0.1'
```

This issue will be resolved when we release the Null Safety version soon.

**Comment by unoravi** [comment]
@are 
I have tried this solution but this doesn't solve issue because there are few packages which has an issue with *crypto: '3.0.1'* Because of few issue and features, I must need to use latest dependencies. So crypto 3.0.1 faces an issue there.

I also hope that the Null Safety version comes soon.
Thanks

**Comment by unoravi** [comment]
This issue restricts me to use another latest dependencies as I have mentioned earlier. So is there any release day/month (approximated) for "Null Safety version" ?

**Comment by mohitpubnub** [comment]
We are almost on the verge of wrapping up final stuffs/checks related to upcoming release!  🤞 
In a day or two, @are  can announce about tentative(or exact) day/month.

**Comment by unoravi** [comment]
@mohitpubnub @are 
Thanks for the info.

**Comment by devopsokdone** [comment]
@mohitpubnub @are 
Eagerly awaiting your update on this.

**Comment by unoravi** [comment]
@are 
Null Safe beta release works properly for now. Please share approx date of final version release if you have any idea.

Thanks for the support..!!
