### ISSUE TITLE
ConcurrentModificationError during pubnub.unsubscribeAll()

### ISSUE THREAD

**Issue by alecxandrys** [pubnub/dart#43]
Good day,
I catch next unhandled error:
![изображение](https://user-images.githubusercontent.com/11788884/115708508-c61b1a00-a378-11eb-9613-a63dbc0eb37d.png)
There is only one unsubscribeAll call in the whole code, and I checked that there is only one call of this part of code in the same time.
 
Call stack:
![изображение](https://user-images.githubusercontent.com/11788884/115709228-a20c0880-a379-11eb-9a76-da595b7ff89b.png)

Variables:
![изображение](https://user-images.githubusercontent.com/11788884/115709407-db447880-a379-11eb-9013-c5ea10c712de.png)

 pubnub: ^3.2.0
 
 flutter doctor -v
![изображение](https://user-images.githubusercontent.com/11788884/115709719-37a79800-a37a-11eb-8904-8677c6a85832.png)

**Comment by are** [comment]
This should be fixed in [v4.0.0-beta.0](https://pub.dev/packages/pubnub/versions/4.0.0-beta.0). Please let us know if that solves your issue.
