### ISSUE TITLE
PushGateway is not accessible

### ISSUE THREAD

**Issue by pushpendraKh** [pubnub/dart#5]
`addPushChannels` requires a gateway of type `PushGateway`. But it is not exposed publicly.

**Comment by aadil058** [comment]
`import 'package:pubnub/src/dx/_endpoints/push.dart';`

**Comment by are** [comment]
Hi @pushpendraKh! Thanks for opening an issue! We are in process of releasing a new version with this fixed, but in the meantime you can import the type directly like @aadil058 suggested.

**Comment by are** [comment]
Fixed in [v1.1.1](https://github.com/pubnub/dart/releases/tag/v1.1.1).

**Comment by pushpendraKh** [comment]
@are you have exposed `PushGatewayExtension` not `PushGateway`.

**Comment by mohitpubnub** [comment]
> @are you have exposed `PushGatewayExtension` not `PushGateway`.

@pushpendraKh  Thanks for pointing it out. Fixing this glitch and others as well.
