### ISSUE TITLE
Reconnect not subscribing to Object Events of the new channel

### ISSUE THREAD

**Issue by devopsokdone** [pubnub/dart#54]
Use case: New channel added to user's Channel Group

We append the channel ID to user's channel group, and fire a reconnect, we are able to receive message, messageAction and Signal but Object Events are not received.

If we Subscribe again to the appended channel group instead of reconnect we are getting the object events as well. 

So we believe something is missing or different in Reconnect, can you please verify and revert.

We are using the Null Safety version.

**Comment by are** [comment]
Hi! This maybe due to an internal delay in the PubNub Network. Unfortunately I cannot help you with this here, but I recommend contacting our excellent [PubNub Support](https://support.pubnub.com/hc/en-us) by submitting a ticket to them or sending an email to support@pubnub.com.
