### ISSUE TITLE
Unhandled Exception: Concurrent modification during iteration: Instance of '_CompactLinkedHashSet<Subscription>'.

### ISSUE THREAD

**Issue by pushpendraKh** [pubnub/dart#6]
Topic: Push Notification
subtopic: Unsubscribe to all the subscribed channels.
Reproducable both on iOS and android.

Description: I want to unsubscribe all the channels. Hence I am using `unsubscribeAll` method. But it is giving the following exception -

Unhandled Exception: Concurrent modification during iteration: Instance of '_CompactLinkedHashSet<Subscription>'.
#0      _CompactIterator.moveNext (dart:collection-patch/compact_hash.dart:455:7)
#1      SubscribeDx.unsubscribeAll.<anonymous closure> (package:pubnub/src/dx/subscribe/subscribe.dart:53:29)
<asynchronous suspension>
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#3      KeysetStore.forEach (package:pubnub/src/core/keyset.dart:76:12)
#4      SubscribeDx.unsubscribeAll (package:pubnub/src/dx/subscribe/subscribe.dart:52:19)

**Comment by pushpendraKh** [comment]
Any update on this?

**Comment by are** [comment]
I am taking care of this right now!
