### ISSUE TITLE
Uploading file in channel throws exception

### ISSUE THREAD

**Issue by rahulrmishra** [pubnub/dart#61]
I need to send a file to a channel but I am not able to figure out how to do it.

First I select the file then I do,

Uint8List fileContent = await selectedFile.readAsBytes();
await pubnub.files.sendFile(channelId, 'smiley.jpg', fileContent );

But I get an error saying PubNubException: request failed (HttpException: HTTP headers are not mutable).

**Comment by are** [comment]
Hello! What version of the SDK are you using?

**Comment by rahulrmishra** [comment]
Hey this is the version - pubnub: ^3.2.0

**Comment by rahulrmishra** [comment]
Can you check if this is a bug or am I implementing it the wrong way?

**Comment by mohitpubnub** [comment]
Have you tried using version `pubnub: ^4.0.0-beta.1` ?

**Comment by rahulrmishra** [comment]
> Have you tried using version `pubnub: ^4.0.0-beta.1` ?

My flutter version is -
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git  
Framework • revision 9b2d32b605 (6 months ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

So I'm getting conflicts while using the 4.0.0-beta,  and I cannot migrate it to flutter 2 right now

**Comment by are** [comment]
We encourage you to migrate to Flutter 2. You don't need to use Null Safety or change your code for this. You can use the latest Flutter and Dart versions and disable the Null Safety. This will allow you to use latest versions of the libraries but migrate your code when you have time to do so.

**Comment by rahulrmishra** [comment]
I migrated to Flutter 2 and started using pubnub: ^4.0.0-beta.1 and now I don't get the exception.
