### ISSUE TITLE
The getter 'messages' isn't defined for the class 'Future<Subscription>'.

### ISSUE THREAD

**Issue by trumanleung** [pubnub/dart#7]
After subscribing to a channel, the Future<Subscription> doesn't have a messages stream. Here's my code. pubnubChannel is a string with the name of the channel. 

```
PubNub pubnub;
Future<Subscription> pubnubsub;
pubnub = PubNub(defaultKeyset: Keyset(subscribeKey: config.pubNubSubscribeKey));
pubnubsub = pubnub.subscribe(channels: { pubnubChannel });
pubnubsub.messages.listen((envelope) {
   print(`${envelope.uuid} sent a message: ${envelope.payload}`);
});

```
I'm getting this error: The getter 'messages' isn't defined for the class 'Future<Subscription>'.

**Comment by are** [comment]
Hi! Thanks for reporting an issue!

This is intended behaviour. `pubnub.subscribe` returns a `Future<Subscription>` and you need to use `await` to unwrap the `Subscription` from the future.

Take a look at this article: https://dart.dev/codelabs/async-await

**Comment by trumanleung** [comment]
Thank you. I added await before the pubnub.subscribe call and it works. Now I can build my Flutter app however occasionally there will be an exception thrown: 

```
Exception has occurred.
DioError (DioError [DioErrorType.DEFAULT]: HttpException: Connection closed before full header was received, uri = https://ps.pndsn.com/v2/subscribe/sub-c-81c1977e-15ff-11e5-b66b-02ee2ddab7fe/familyUser-22/0?tt=15914051777763439&tr=2&pnsdk=PubNub-Dart%2F1.1.3)
```

I understand that Dio is a dependency of this package. Do you have a working Flutter app example with code on Github that I can take a look at to see how to get passed this DioError?
